<h1>Flight Fare Prediction</h1>

<h3>Data pre-processing</h3>

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv(r'/Users/kiahvaidya/Desktop/flightfare/Cleaned_dataset.csv')

In [5]:
df.head()

,Date_of_journey,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare
0,2023-01-16,Monday,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335
1,2023-01-16,Monday,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899
2,2023-01-16,Monday,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801
3,2023-01-16,Monday,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794
4,2023-01-16,Monday,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955

In [6]:
df.tail()

,Date_of_journey,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare
452083,2023-03-06,Monday,Vistara,UK-926,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,13.0833,50,65028
452084,2023-03-06,Monday,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254
452085,2023-03-06,Monday,Vistara,UK-918,Business,Ahmedabad,Before 6 AM,1-stop,12 PM - 6 PM,Chennai,11.2500,50,69254
452086,2023-03-06,Monday,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980
452087,2023-03-06,Monday,Vistara,UK-946,Business,Ahmedabad,6 AM - 12 PM,1-stop,After 6 PM,Chennai,11.1667,50,72980

In [7]:
df.drop('Date_of_journey',axis=1, inplace=True)

In [8]:
df.head()

,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare
0,Monday,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335
1,Monday,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899
2,Monday,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801
3,Monday,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794
4,Monday,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955

In [9]:
day_dummies = pd.get_dummies(df['Journey_day'], prefix='day')
df = pd.concat([df, day_dummies], axis=1)

In [10]:
df.head()

,Journey_day,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday
0,Monday,SpiceJet,SG-8169,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,False,True,False,False,False,False,False
1,Monday,Indigo,6E-2519,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,False,True,False,False,False,False,False
2,Monday,GO FIRST,G8-354,Economy,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,False,True,False,False,False,False,False
3,Monday,SpiceJet,SG-8709,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,False,True,False,False,False,False,False
4,Monday,Air India,AI-805,Economy,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,False,True,False,False,False,False,False

In [11]:
df.drop('Journey_day',axis=1, inplace=True)

In [12]:
df['day_Friday'] = df['day_Friday'].astype(int)
df['day_Monday'] = df['day_Monday'].astype(int)
df['day_Tuesday'] = df['day_Tuesday'].astype(int)
df['day_Wednesday'] = df['day_Wednesday'].astype(int)
df['day_Thursday'] = df['day_Thursday'].astype(int)
df['day_Saturday'] = df['day_Saturday'].astype(int)
df['day_Sunday'] = df['day_Sunday'].astype(int)

In [13]:
df['Class'] = df['Class'].map({'Business': 1, 'Economy': 0})

In [14]:
df.head()

,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday
0,SpiceJet,SG-8169,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,0,1,0,0,0,0,0
1,Indigo,6E-2519,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,0,1,0,0,0,0,0
2,GO FIRST,G8-354,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,0,1,0,0,0,0,0
3,SpiceJet,SG-8709,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,0,1,0,0,0,0,0
4,Air India,AI-805,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,0,1,0,0,0,0,0

In [15]:
df = df.loc[:, ~df.T.duplicated()]

In [16]:
df.head()

,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,day_Sunday,day_Thursday,day_Tuesday,day_Wednesday
0,SpiceJet,SG-8169,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,0,1,0,0,0,0,0
1,Indigo,6E-2519,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,0,1,0,0,0,0,0
2,GO FIRST,G8-354,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,0,1,0,0,0,0,0
3,SpiceJet,SG-8709,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,0,1,0,0,0,0,0
4,Air India,AI-805,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,0,1,0,0,0,0,0

In [17]:
source_dummies = pd.get_dummies(df['Source'], prefix='source')
df = pd.concat([df, source_dummies], axis=1)

In [18]:
df.head()

,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,...,day_Thursday,day_Tuesday,day_Wednesday,source_Ahmedabad,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai
0,SpiceJet,SG-8169,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,...,0,0,0,False,False,False,True,False,False,False
1,Indigo,6E-2519,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,...,0,0,0,False,False,False,True,False,False,False
2,GO FIRST,G8-354,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,...,0,0,0,False,False,False,True,False,False,False
3,SpiceJet,SG-8709,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,...,0,0,0,False,False,False,True,False,False,False
4,Air India,AI-805,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,...,0,0,0,False,False,False,True,False,False,False

In [19]:
df['source_Ahmedabad'] = df['source_Ahmedabad'].astype(int)
df['source_Mumbai'] = df['source_Mumbai'].astype(int)
df['source_Delhi'] = df['source_Delhi'].astype(int)
df['source_Bangalore'] = df['source_Bangalore'].astype(int)
df['source_Chennai'] = df['source_Chennai'].astype(int)
df['source_Kolkata'] = df['source_Kolkata'].astype(int)
df['source_Hyderabad'] = df['source_Hyderabad'].astype(int)

In [20]:
df.head()

,Airline,Flight_code,Class,Source,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,...,day_Thursday,day_Tuesday,day_Wednesday,source_Ahmedabad,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai
0,SpiceJet,SG-8169,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,...,0,0,0,0,0,0,1,0,0,0
1,Indigo,6E-2519,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,...,0,0,0,0,0,0,1,0,0,0
2,GO FIRST,G8-354,0.0,Delhi,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,...,0,0,0,0,0,0,1,0,0,0
3,SpiceJet,SG-8709,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,...,0,0,0,0,0,0,1,0,0,0
4,Air India,AI-805,0.0,Delhi,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,...,0,0,0,0,0,0,1,0,0,0

In [21]:
df.drop('Source',axis=1, inplace=True)

In [22]:
df.head()

,Airline,Flight_code,Class,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,...,day_Thursday,day_Tuesday,day_Wednesday,source_Ahmedabad,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai
0,SpiceJet,SG-8169,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,...,0,0,0,0,0,0,1,0,0,0
1,Indigo,6E-2519,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,...,0,0,0,0,0,0,1,0,0,0
2,GO FIRST,G8-354,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,...,0,0,0,0,0,0,1,0,0,0
3,SpiceJet,SG-8709,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,...,0,0,0,0,0,0,1,0,0,0
4,Air India,AI-805,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,...,0,0,0,0,0,0,1,0,0,0

In [23]:
departure_dummies = pd.get_dummies(df['Departure'], prefix='departure')
df = pd.concat([df, departure_dummies], axis=1)

In [24]:
df.head()

,Airline,Flight_code,Class,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,...,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai,departure_12 PM - 6 PM,departure_6 AM - 12 PM,departure_After 6 PM,departure_Before 6 AM
0,SpiceJet,SG-8169,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,...,0,0,1,0,0,0,False,False,True,False
1,Indigo,6E-2519,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,...,0,0,1,0,0,0,False,False,True,False
2,GO FIRST,G8-354,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,...,0,0,1,0,0,0,False,False,True,False
3,SpiceJet,SG-8709,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,...,0,0,1,0,0,0,False,False,True,False
4,Air India,AI-805,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,...,0,0,1,0,0,0,False,False,True,False

In [25]:
df['departure_12 PM - 6 PM'] = df['departure_12 PM - 6 PM'].astype(int)
df['departure_6 AM - 12 PM'] = df['departure_6 AM - 12 PM'].astype(int)
df['departure_After 6 PM'] = df['departure_After 6 PM'].astype(int)
df['departure_Before 6 AM'] = df['departure_Before 6 AM'].astype(int)

In [26]:
df.head()

,Airline,Flight_code,Class,Departure,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,...,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai,departure_12 PM - 6 PM,departure_6 AM - 12 PM,departure_After 6 PM,departure_Before 6 AM
0,SpiceJet,SG-8169,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5335,...,0,0,1,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,...,0,0,1,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,After 6 PM,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,...,0,0,1,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.0833,1,5794,...,0,0,1,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,After 6 PM,non-stop,After 6 PM,Mumbai,2.1667,1,5955,...,0,0,1,0,0,0,0,0,1,0

In [27]:
df.drop('Departure',axis=1, inplace=True)

In [28]:
df.head()

,Airline,Flight_code,Class,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,day_Friday,...,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai,departure_12 PM - 6 PM,departure_6 AM - 12 PM,departure_After 6 PM,departure_Before 6 AM
0,SpiceJet,SG-8169,0.0,non-stop,After 6 PM,Mumbai,2.0833,1,5335,0,...,0,0,1,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,non-stop,Before 6 AM,Mumbai,2.3333,1,5899,0,...,0,0,1,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,non-stop,Before 6 AM,Mumbai,2.1667,1,5801,0,...,0,0,1,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,non-stop,After 6 PM,Mumbai,2.0833,1,5794,0,...,0,0,1,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,non-stop,After 6 PM,Mumbai,2.1667,1,5955,0,...,0,0,1,0,0,0,0,0,1,0

In [29]:
df['Total_stops'] = df['Total_stops'].map({'non-stop': 0, '1-stop': 1,'2+-stop' : 2})

In [30]:
df.head()

,Airline,Flight_code,Class,Total_stops,Arrival,Destination,Duration_in_hours,Days_left,Fare,day_Friday,...,source_Bangalore,source_Chennai,source_Delhi,source_Hyderabad,source_Kolkata,source_Mumbai,departure_12 PM - 6 PM,departure_6 AM - 12 PM,departure_After 6 PM,departure_Before 6 AM
0,SpiceJet,SG-8169,0.0,0,After 6 PM,Mumbai,2.0833,1,5335,0,...,0,0,1,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,Before 6 AM,Mumbai,2.3333,1,5899,0,...,0,0,1,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,0,Before 6 AM,Mumbai,2.1667,1,5801,0,...,0,0,1,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,0,After 6 PM,Mumbai,2.0833,1,5794,0,...,0,0,1,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,0,After 6 PM,Mumbai,2.1667,1,5955,0,...,0,0,1,0,0,0,0,0,1,0

In [31]:
arrival_dummies = pd.get_dummies(df['Arrival'], prefix='arrival')
df = pd.concat([df, arrival_dummies], axis=1)

In [32]:
df['arrival_12 PM - 6 PM'] = df['arrival_12 PM - 6 PM'].astype(int)
df['arrival_6 AM - 12 PM'] = df['arrival_6 AM - 12 PM'].astype(int)
df['arrival_After 6 PM'] = df['arrival_After 6 PM'].astype(int)
df['arrival_Before 6 AM'] = df['arrival_Before 6 AM'].astype(int)

In [33]:
df.drop('Arrival',axis=1, inplace=True)

In [34]:
df.head()

,Airline,Flight_code,Class,Total_stops,Destination,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,...,source_Kolkata,source_Mumbai,departure_12 PM - 6 PM,departure_6 AM - 12 PM,departure_After 6 PM,departure_Before 6 AM,arrival_12 PM - 6 PM,arrival_6 AM - 12 PM,arrival_After 6 PM,arrival_Before 6 AM
0,SpiceJet,SG-8169,0.0,0,Mumbai,2.0833,1,5335,0,1,...,0,0,0,0,1,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,Mumbai,2.3333,1,5899,0,1,...,0,0,0,0,1,0,0,0,0,1
2,GO FIRST,G8-354,0.0,0,Mumbai,2.1667,1,5801,0,1,...,0,0,0,0,1,0,0,0,0,1
3,SpiceJet,SG-8709,0.0,0,Mumbai,2.0833,1,5794,0,1,...,0,0,0,0,1,0,0,0,1,0
4,Air India,AI-805,0.0,0,Mumbai,2.1667,1,5955,0,1,...,0,0,0,0,1,0,0,0,1,0

In [35]:
destination_dummies = pd.get_dummies(df['Destination'], prefix='destination')
df = pd.concat([df, destination_dummies], axis=1)

In [36]:
df['destinatiom_Ahmedabad'] = df['destination_Ahmedabad'].astype(int)
df['destination_Mumbai'] = df['destination_Mumbai'].astype(int)
df['destination_Delhi'] = df['destination_Delhi'].astype(int)
df['destination_Bangalore'] = df['destination_Bangalore'].astype(int)
df['destination_Chennai'] = df['destination_Chennai'].astype(int)
df['destination_Kolkata'] = df['destination_Kolkata'].astype(int)
df['destination_Hyderabad'] = df['destination_Hyderabad'].astype(int)

In [37]:
df.drop('Destination',axis=1, inplace=True)

In [38]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai,destinatiom_Ahmedabad
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,1,0,False,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,1,False,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,1,False,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,1,0,False,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,1,0,False,0,0,0,0,0,1,0

In [39]:
pip install scikit-learn

Requirement already satisfied: scikit-learn in ./env/lib/python3.13/site-packages (1.7.0)
Requirement already satisfied: numpy>=1.22.0 in ./env/lib/python3.13/site-packages (from scikit-learn) (2.3.1)
Requirement already satisfied: scipy>=1.8.0 in ./env/lib/python3.13/site-packages (from scikit-learn) (1.16.0)
Requirement already satisfied: joblib>=1.2.0 in ./env/lib/python3.13/site-packages (from scikit-learn) (1.5.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./env/lib/python3.13/site-packages (from scikit-learn) (3.6.0)
Note: you may need to restart the kernel to use updated packages.

In [40]:
pip install xgboost

Requirement already satisfied: xgboost in ./env/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy in ./env/lib/python3.13/site-packages (from xgboost) (2.3.1)
Requirement already satisfied: scipy in ./env/lib/python3.13/site-packages (from xgboost) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [41]:
X = df.drop('Fare', axis=1)
y = df['Fare']

In [42]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai,destinatiom_Ahmedabad
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,1,0,False,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,1,False,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,1,False,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,1,0,False,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,1,0,False,0,0,0,0,0,1,0

In [43]:
df['destinatiom_Ahmedabad'] = df['destination_Ahmedabad'].astype(int)

In [44]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai,destinatiom_Ahmedabad
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,1,0,False,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,1,False,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,1,False,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,1,0,False,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,1,0,False,0,0,0,0,0,1,0

In [45]:
df = df.loc[:, ~df.T.duplicated()]

In [46]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_6 AM - 12 PM,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,0,1,0,False,0,0,0,0,0,1
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,0,1,False,0,0,0,0,0,1
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,0,1,False,0,0,0,0,0,1
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,0,1,0,False,0,0,0,0,0,1
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,0,1,0,False,0,0,0,0,0,1

In [47]:
df['destinatiom_Ahmedabad'] = df['destination_Ahmedabad'].astype(int)

In [48]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai,destinatiom_Ahmedabad
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,1,0,False,0,0,0,0,0,1,0
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,1,False,0,0,0,0,0,1,0
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,1,False,0,0,0,0,0,1,0
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,1,0,False,0,0,0,0,0,1,0
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,1,0,False,0,0,0,0,0,1,0

In [49]:
df = df.loc[:, ~df.T.duplicated()]

In [50]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_6 AM - 12 PM,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,0,1,0,False,0,0,0,0,0,1
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,0,1,False,0,0,0,0,0,1
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,0,1,False,0,0,0,0,0,1
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,0,1,0,False,0,0,0,0,0,1
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,0,1,0,False,0,0,0,0,0,1

In [51]:
df['destination_Ahmedabad'] = df['destination_Ahmedabad'].astype(int)

In [52]:
df.head()

,Airline,Flight_code,Class,Total_stops,Duration_in_hours,Days_left,Fare,day_Friday,day_Monday,day_Saturday,...,arrival_6 AM - 12 PM,arrival_After 6 PM,arrival_Before 6 AM,destination_Ahmedabad,destination_Bangalore,destination_Chennai,destination_Delhi,destination_Hyderabad,destination_Kolkata,destination_Mumbai
0,SpiceJet,SG-8169,0.0,0,2.0833,1,5335,0,1,0,...,0,1,0,0,0,0,0,0,0,1
1,Indigo,6E-2519,0.0,0,2.3333,1,5899,0,1,0,...,0,0,1,0,0,0,0,0,0,1
2,GO FIRST,G8-354,0.0,0,2.1667,1,5801,0,1,0,...,0,0,1,0,0,0,0,0,0,1
3,SpiceJet,SG-8709,0.0,0,2.0833,1,5794,0,1,0,...,0,1,0,0,0,0,0,0,0,1
4,Air India,AI-805,0.0,0,2.1667,1,5955,0,1,0,...,0,1,0,0,0,0,0,0,0,1

In [53]:
X = df.drop(['Fare', 'Airline', 'Flight_code'], axis=1)

<h3>Model Training</h3>

<h4>1.Random Forest Regrerssor</h4>

In [54]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [56]:
model_rf = RandomForestRegressor(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [57]:
y_pred_rf = model_rf.predict(X_test)

In [58]:
print("Random Forest:")
print("MAE:", mean_absolute_error(y_test, y_pred_rf))
print("R²:", r2_score(y_test, y_pred_rf))

Random Forest:
MAE: 2994.8755604931675
R²: 0.9296175359482872

In [59]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
print("RMSE:", rmse)

RMSE: 5389.297041442616

<h4>2.XG Boost</h4>

In [60]:

pip install xgboost

Requirement already satisfied: xgboost in ./env/lib/python3.13/site-packages (3.0.2)
Requirement already satisfied: numpy in ./env/lib/python3.13/site-packages (from xgboost) (2.3.1)
Requirement already satisfied: scipy in ./env/lib/python3.13/site-packages (from xgboost) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [61]:
!brew install libomp

==> Downloading https://formulae.brew.sh/api/formula.jws.json
==> Downloading https://formulae.brew.sh/api/cask.jws.json
Warning: libomp 20.1.7 is already installed and up-to-date.
To reinstall 20.1.7, run:
  brew reinstall libomp

In [62]:
from xgboost import XGBRegressor

In [63]:
model_xgb = XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=5, random_state=42)
model_xgb.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.1, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [64]:
y_pred_xgb = model_xgb.predict(X_test)

In [65]:
print("XGBoost:")
print("MAE:", mean_absolute_error(y_test, y_pred_xgb))
print("R²:", r2_score(y_test, y_pred_xgb))

XGBoost:
MAE: 3978.302490234375
R²: 0.8964546918869019

In [66]:
rmse = np.sqrt(mean_squared_error(y_test, y_pred_rf))
print("RMSE:", rmse)

RMSE: 5389.297041442616

<h3>Conclusion</h3>

<p>In this Flight Fare Prediction project, we used machine learning techniques to estimate flight ticket prices using features like airline, source, destination, duration, and more. Two models were implemented and compared:

Random Forest Regressor

XGBoost Regressor

Based on the evaluation metrics — Mean Absolute Error (MAE), Root Mean Squared Error (RMSE), and R² score — the Random Forest Regressor outperformed XGBoost, achieving a higher R² value and lower error rates. This suggests it was better at capturing patterns in the dataset and generalizing to unseen data.

Random Forest proved to be the most effective model for our flight fare prediction problem, and with further improvements like hyperparameter tuning, feature selection, and scaling, performance can be enhanced further.

</p>